### PR TITLE
Add missing config key when querying the phone number

### LINKED ISSUE #13: Some questions (not active but.., user's account phone num, re-send button)
SMS idea is very good! I love it & used.

1. User's TOTP option is **not** active but application require SMS code from user during login page.
2. Instead of manually adding the phone number to the database, Is it possible to use the phone number on the account of the user?
3. Sometimes the SMS code is not sent, can you add re-send button? _(It will be active after 30 sec or 1 minute)_
4. Need to be used with [twofactor_totp](https://github.com/nextcloud/twofactor_totp)?

Thank you @ChristophWurst

### PR DESCRIPTION
**Pull request by ChristophWurst**
@emresaracoglu please review and test :-)

Fixes #13

### CODE REVIEW

**Comment by emresaracoglu** [comment]
If the phone number of the user is unregistered, he login in directly.. Working!
Thank you:)

**Comment by ChristophWurst** [comment]
Great :-)

**Comment by ChristophWurst** [comment]
btw I've added you as collaborator so you can create and review PRs too :-)

**Comment by emresaracoglu** [comment]
I'm honored, thank you @ChristophWurst

**Pull request merged**
