### PR TITLE
Update to 11

### PR DESCRIPTION
**Pull request by LukasReschke**
For https://github.com/nextcloud/server/pull/2139

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Comment by MorrisJobke** [comment]
👍

**Comment by ChristophWurst** [comment]
👍 thanks. will rebase/merge as soon as nextcloud/server#2139 was merged into master so that CI tests pass here.

**Comment by MorrisJobke** [comment]
Merged -> I restarted the build

**Pull request merged**
