### PR TITLE
Telegram integration

### PR DESCRIPTION
**Pull request by ChristophWurst**
This was developed by @Dretech. Since I could not push to #27, I've created this PR to fix the coding style and make use of the HTTP client for the Telegram API call.

@Dretech please test again. I do not use/have Telegram so I cannot.

### CODE REVIEW

**Comment by Dretech** [comment]
Christoph, I added your name for collaborating my fork of 2factor sms.

What do you want to test again? I tested the Telegram 2 factor authentication and it is still working.

André

**Comment by MariusBluem** [comment]
Why do you want to have telegram in twofactor_sms? would a seperate twofactor_telegram app not make more sense?

**Comment by ChristophWurst** [comment]
> Why do you want to have telegram in twofactor_sms? would a seperate twofactor_telegram app not make more sense?

No. Because this is a generic app for any external messaging gateways. One could rename it to `twofactor_external`.

**Comment by Dretech** [comment]
I also made a very small general app for two factor authentication with Nextcloud, see: [](https://sourceforge.net/projects/php-functions-2fa-telegram/)

**Comment by Dretech** [comment]
@ChristophWurst would you reply to my message of 17 days ago? Thanks in advance.

**Pull request merged**
